from fastapi import APIRouter, Depends, Query
from bson import ObjectId
from datetime import datetime, timezone

from core.database import get_db
from core.security import get_current_user
from core.utils import serialize_doc, serialize_docs

router = APIRouter(prefix="/api/feed", tags=["feed"])


@router.get("/")
async def get_feed(
    skip:  int = Query(0,  ge=0),
    limit: int = Query(20, ge=1, le=100),
    current_user=Depends(get_current_user),
    db=Depends(get_db),
):
    """
    Returns the activity feed for the current user —
    events generated by people they follow, newest first.
    """
    following_ids = current_user.get("following") or []

    cursor = (
        db.activity.find({"userId": {"$in": following_ids}})
        .sort("createdAt", -1)
        .skip(skip)
        .limit(limit)
    )
    events = await cursor.to_list(length=limit)
    total  = await db.activity.count_documents({"userId": {"$in": following_ids}})

    return {
        "total":   total,
        "skip":    skip,
        "limit":   limit,
        "results": serialize_docs(events),
    }


@router.get("/me")
async def get_my_activity(
    skip:  int = Query(0,  ge=0),
    limit: int = Query(20, ge=1, le=100),
    current_user=Depends(get_current_user),
    db=Depends(get_db),
):
    """Returns the current user's own activity history."""
    cursor = (
        db.activity.find({"userId": current_user["_id"]})
        .sort("createdAt", -1)
        .skip(skip)
        .limit(limit)
    )
    events = await cursor.to_list(length=limit)
    total  = await db.activity.count_documents({"userId": current_user["_id"]})

    return {
        "total":   total,
        "skip":    skip,
        "limit":   limit,
        "results": serialize_docs(events),
    }
