from fastapi import APIRouter, Depends, Query
from bson import ObjectId
from datetime import datetime, timezone

from core.database import get_db
from core.security import get_current_user
from core.utils import serialize_doc, serialize_docs

router = APIRouter(prefix="/api/feed", tags=["feed"])

# Maps the frontend `sort` query value to a MongoDB sort field. Every option
# sorts descending; a stable `_id` tiebreaker keeps pagination consistent.
REVIEW_SORTS = {
    "recent":     "createdAt",
    "overall":    "overallScore",
    "gameplay":   "gameplay",
    "content":    "content",
    "narrative":  "narrative",
    "aesthetics": "aesthetics",
    "polish":     "polish",
}


@router.get("/")
async def get_feed(
    skip:  int = Query(0,  ge=0),
    limit: int = Query(20, ge=1, le=100),
    current_user=Depends(get_current_user),
    db=Depends(get_db),
):
    """
    Returns the activity feed for the current user —
    events generated by people they follow, newest first.
    """
    following_ids = current_user.get("following") or []

    cursor = (
        db.activity.find({"userId": {"$in": following_ids}})
        .sort("createdAt", -1)
        .skip(skip)
        .limit(limit)
    )
    events = await cursor.to_list(length=limit)
    total  = await db.activity.count_documents({"userId": {"$in": following_ids}})

    return {
        "total":   total,
        "skip":    skip,
        "limit":   limit,
        "results": serialize_docs(events),
    }


@router.get("/me")
async def get_my_activity(
    skip:  int = Query(0,  ge=0),
    limit: int = Query(20, ge=1, le=100),
    current_user=Depends(get_current_user),
    db=Depends(get_db),
):
    """Returns the current user's own activity history."""
    cursor = (
        db.activity.find({"userId": current_user["_id"]})
        .sort("createdAt", -1)
        .skip(skip)
        .limit(limit)
    )
    events = await cursor.to_list(length=limit)
    total  = await db.activity.count_documents({"userId": current_user["_id"]})

    return {
        "total":   total,
        "skip":    skip,
        "limit":   limit,
        "results": serialize_docs(events),
    }


@router.get("/reviews")
async def get_following_reviews(
    skip:      int = Query(0,  ge=0),
    limit:     int = Query(20, ge=1, le=100),
    sort:      str = Query("recent"),
    direction: str = Query("desc"),
    current_user=Depends(get_current_user),
    db=Depends(get_db),
):
    """
    Returns reviews written by users the current user follows.
    Sort field is controlled by `sort` (see REVIEW_SORTS) and order by
    `direction` (asc/desc). Each review is enriched with game and reviewer
    info so the frontend doesn't need N+1 round-trips.
    """
    following_ids = current_user.get("following") or []
    if not following_ids:
        return {"total": 0, "skip": skip, "limit": limit, "results": []}

    sort_field = REVIEW_SORTS.get(sort, "createdAt")
    sort_dir   = 1 if direction == "asc" else -1

    filt = {"userId": {"$in": following_ids}}
    cursor = (
        db.reviews.find(filt)
        .sort([(sort_field, sort_dir), ("_id", -1)])
        .skip(skip)
        .limit(limit)
    )
    reviews_raw = await cursor.to_list(length=limit)
    total       = await db.reviews.count_documents(filt)

    if not reviews_raw:
        return {"total": total, "skip": skip, "limit": limit, "results": []}

    # Batch-fetch related games + reviewer users for enrichment
    game_ids = list({r["gameId"] for r in reviews_raw if r.get("gameId")})
    user_ids = list({r["userId"] for r in reviews_raw if r.get("userId")})

    games_map: dict = {}
    if game_ids:
        async for g in db.games.find(
            {"_id": {"$in": game_ids}},
            {"_id": 1, "name": 1, "coverUrl": 1},
        ):
            games_map[g["_id"]] = g

    users_map: dict = {}
    if user_ids:
        async for u in db.users.find(
            {"_id": {"$in": user_ids}},
            {"_id": 1, "username": 1, "preferences": 1},
        ):
            users_map[u["_id"]] = u

    enriched = []
    for r in reviews_raw:
        doc = serialize_doc(r)
        g   = games_map.get(r.get("gameId"))
        if g:
            doc["gameName"]     = g.get("name")
            doc["gameCoverUrl"] = g.get("coverUrl")
        u = users_map.get(r.get("userId"))
        if u:
            prefs = u.get("preferences") or {}
            doc["reviewer"] = {
                "username":       u.get("username"),
                "displayName":    prefs.get("displayName"),
                "profilePicture": prefs.get("profilePicture"),
            }
        enriched.append(doc)

    return {"total": total, "skip": skip, "limit": limit, "results": enriched}
